[workspace]
git_tag_name = "{{ package }}/v{{ version }}"
git_release_draft = true
release_always = true
publish_no_verify = true

[[package]]
name = "trustless-backend-lambda"
publish = false
git_tag_enable = false
git_release_enable = false
