name: ci

on:
  push:
    branches: [main,ci]

jobs:
  test:
    uses: ./.github/workflows/_test.yml
    with:
      build: true

  release:
    needs: [test]
    uses: ./.github/workflows/_release.yml
    secrets: inherit
    permissions:
      contents: write
      id-token: write
      actions: read
      attestations: write
