name: release-plz-pr

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  id-token: write

jobs:
  release-plz-pr:
    runs-on: ubuntu-latest
    environment:
      name: crates-io
    steps:
      - uses: sorah/sts-cat/.github/actions/exchange-token@27da2b9cda39fc45c2020c0fb65865d4e440391b
        id: generate-token
        with:
          endpoint: ${{ secrets.STS_CAT_ENDPOINT }}
          scope: ${{ github.repository }}
          identity: release
          audience: https://sts-cat.nkmi.me
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          token: ${{ steps.generate-token.outputs.token }}
      - uses: dtolnay/rust-toolchain@stable
      - uses: rust-lang/crates-io-auth-action@b7e9a28eded4986ec6b1fa40eeee8f8f165559ec # v1.0.3
        id: auth
      - uses: release-plz/action@1528104d2ca23787631a1c1f022abb64b34c1e11 # v0.5.128
        with:
          command: release-pr
        env:
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
          CARGO_REGISTRY_TOKEN: ${{ steps.auth.outputs.token }}
